/**
 * Vitest CI area partition — every src test file appears in exactly one area,
 * except functional-fixtures-only files (run via test:functional-fixtures).
 */
export const FUNCTIONAL_FIXTURES_ONLY = [
    'src/test-harness/scenario.test.ts',
    'src/search-regression.test.ts',
    'src/test-harness/functional-telemetry/validate-fixture.test.ts',
    'src/test-harness/functional-core/functional-queries.harness.test.ts',
] as const;

export const CI_TEST_AREAS = {
    'index-store': [
        'src/applydelta-coherence.test.ts',
        'src/atomic-commit.test.ts',
        'src/atoms.test.ts',
        'src/base-extractor.test.ts',
        'src/boot-session.test.ts',
        'src/bucket.test.ts',
        'src/catchup-scheduling.test.ts',
        'src/catchup.test.ts',
        'src/chunk-diff.test.ts',
        'src/chunker-idpin.test.ts',
        'src/chunker.test.ts',
        'src/db-upgrade.test.ts',
        'src/dim-consistency.test.ts',
        'src/drift-recovery-coordinator.test.ts',
        'src/drift-recovery.test.ts',
        'src/frame-incremental.test.ts',
        'src/identity.test.ts',
        'src/idb-lifecycle-lock.test.ts',
        'src/index-coordinator.test.ts',
        'src/index-delta-view.test.ts',
        'src/index-eta.test.ts',
        'src/index-notice.test.ts',
        'src/index-size.test.ts',
        'src/index-status-bar.test.ts',
        'src/index-status-contract.test.ts',
        'src/index-status-settings.test.ts',
        'src/index-store-count.test.ts',
        'src/index-store-ensure-open.test.ts',
        'src/index-store-lock-retry.test.ts',
        'src/index-store-split.test.ts',
        'src/index-store.test.ts',
        'src/lifecycle-sequence.test.ts',
        'src/offmutex-flush.test.ts',
        'src/persist-cache-startup.test.ts',
        'src/quota-preempt.test.ts',
        'src/sidecar-coordinator.test.ts',
        'src/sidecar-sync.test.ts',
        'src/sidecar.test.ts',
        'src/workflow-coordinator.test.ts',
    ],
    search: [
        'src/bm25-boosts.test.ts',
        'src/bm25-incremental.test.ts',
        'src/bm25-persist.test.ts',
        'src/bm25.test.ts',
        'src/binary-scorer.test.ts',
        'src/binary.test.ts',
        'src/dense-clean.test.ts',
        'src/dense-stats.test.ts',
        'src/folder-coverage.test.ts',
        'src/fusion.test.ts',
        'src/highlight.test.ts',
        'src/name-match.test.ts',
        'src/passage.test.ts',
        'src/pipeline-stage.test.ts',
        'src/quant.test.ts',
        'src/query-field.test.ts',
        'src/query-parser.test.ts',
        'src/ranker.test.ts',
        'src/resident-rerank.test.ts',
        'src/result-aliases.test.ts',
        'src/search-early-name.test.ts',
        'src/search-exclusions.test.ts',
        'src/search-modal-hotkeys.test.ts',
        'src/search-modal-size.test.ts',
        'src/search-modal-tab-dispatch.test.ts',
        'src/search-pipeline-sequence.test.ts',
        'src/select.test.ts',
        'src/snippet.test.ts',
        'src/suggest.test.ts',
        'src/synonyms.test.ts',
        'src/tag-grammar.test.ts',
        'src/text-search-mode.test.ts',
        'src/title-nav-coverage.test.ts',
        'src/token-budget.test.ts',
        'src/tokenize.test.ts',
        'src/vault-lex.test.ts',
    ],
    'cli-ux': [
        'src/cli-handlers.test.ts',
        'src/confirm-modal.test.ts',
        'src/insert-link.test.ts',
        'src/layout-ready.test.ts',
        'src/open-recovery.test.ts',
        'src/open-target.test.ts',
    ],
    platform: [
        'src/diagnostic-report.test.ts',
        'src/embedder-lifecycle.test.ts',
        'src/embedder.test.ts',
        'src/forensics.test.ts',
        'src/gzip.test.ts',
        'src/iframe-runner.test.ts',
        'src/json-text.test.ts',
        'src/logger.test.ts',
        'src/model-registry.test.ts',
        'src/pacer.test.ts',
        'src/perf-console.test.ts',
        'src/platform.test.ts',
        'src/plugin-schedulers.test.ts',
        'src/pool.test.ts',
        'src/prop-normalize.test.ts',
        'src/recents.test.ts',
        'src/redact.test.ts',
        'src/session-telemetry.test.ts',
        'src/settings-migrate.test.ts',
        'src/stall-pattern.test.ts',
        'src/startup-drain.test.ts',
        'src/task-context.test.ts',
        'src/test-harness/functional-telemetry/parse-functional-trace.test.ts',
        'src/test-harness/startup-metrics/startup-metrics.test.ts',
        'src/test-harness/startup-response/modal-ready-contract.test.ts',
        'src/test-harness/startup-response/startup-response.test.ts',
        'scripts/ci/e2e-triage.test.ts',
    ],
} as const;

export type CiTestArea = keyof typeof CI_TEST_AREAS;
