/**
 * Vitest CI area partition — every src test file appears in exactly one area,
 * except functional-fixtures-only files (run via test:functional-fixtures).
 */
export const FUNCTIONAL_FIXTURES_ONLY = [
    'src/search/search-regression.test.ts',
    'src/test-harness/functional-core/functional-queries.harness.test.ts',
    'src/test-harness/functional-telemetry/validate-fixture.test.ts',
    'src/test-harness/scenario.test.ts',
] as const;

export const CI_TEST_AREAS = {
    'index-store': [
        'src/app/boot-session.test.ts',
        'src/app/catchup-scheduling.test.ts',
        'src/app/drift-recovery-coordinator.test.ts',
        'src/app/idb-lifecycle-lock.test.ts',
        'src/app/lifecycle-sequence.test.ts',
        'src/app/workflow-coordinator.test.ts',
        'src/embedding/bucket.test.ts',
        'src/embedding/dim-consistency.test.ts',
        'src/index/atomic-commit.test.ts',
        'src/index/atoms.test.ts',
        'src/index/base-extractor.test.ts',
        'src/index/catchup.test.ts',
        'src/index/chunk-diff.test.ts',
        'src/index/chunker-idpin.test.ts',
        'src/index/chunker.test.ts',
        'src/index/db-upgrade.test.ts',
        'src/index/identity.test.ts',
        'src/index/index-coordinator.test.ts',
        'src/index/index-delta-view.test.ts',
        'src/index/index-size.test.ts',
        'src/index/index-store-count.test.ts',
        'src/index/index-store-ensure-open.test.ts',
        'src/index/index-store-lock-retry.test.ts',
        'src/index/index-store-split.test.ts',
        'src/index/index-store-timeout.test.ts',
        'src/index/index-store-wedge-lock.test.ts',
        'src/index/index-store.test.ts',
        'src/index/quota-preempt.test.ts',
        'src/index/sign-frame-startup.test.ts',
        'src/search/applydelta-coherence.test.ts',
        'src/search/drift-recovery.test.ts',
        'src/search/frame-incremental.test.ts',
        'src/search/offmutex-flush.test.ts',
        'src/search/persist-cache-startup.test.ts',
        'src/sidecar/sidecar-coordinator.test.ts',
        'src/sidecar/sidecar-sync.test.ts',
        'src/sidecar/sidecar.test.ts',
        'src/ui/index-eta.test.ts',
        'src/ui/index-notice.test.ts',
        'src/ui/index-status-bar.test.ts',
        'src/ui/index-status-contract.test.ts',
        'src/ui/index-status-settings.test.ts',
    ],
    'search': [
        'src/embedding/binary-scorer.test.ts',
        'src/embedding/binary.test.ts',
        'src/embedding/quant.test.ts',
        'src/index/folder-coverage.test.ts',
        'src/index/sign-frame-persist.test.ts',
        'src/index/token-budget.test.ts',
        'src/render/highlight.test.ts',
        'src/render/name-match.test.ts',
        'src/render/passage.test.ts',
        'src/render/result-aliases.test.ts',
        'src/render/snippet.test.ts',
        'src/search/bm25-boosts.test.ts',
        'src/search/bm25-incremental.test.ts',
        'src/search/bm25-persist.test.ts',
        'src/search/bm25.test.ts',
        'src/search/dense-clean.test.ts',
        'src/search/dense-stats.test.ts',
        'src/search/fusion.test.ts',
        'src/search/pipeline-stage.test.ts',
        'src/search/query-parser.test.ts',
        'src/search/ranker.test.ts',
        'src/search/resident-rerank.test.ts',
        'src/search/search-early-name.test.ts',
        'src/search/search-exclusions.test.ts',
        'src/search/search-pipeline-sequence.test.ts',
        'src/search/select.test.ts',
        'src/search/suggest.test.ts',
        'src/search/synonyms.test.ts',
        'src/search/tag-grammar.test.ts',
        'src/search/text-search-mode.test.ts',
        'src/search/tokenize.test.ts',
        'src/search/vault-lex.test.ts',
        'src/ui/query-field.test.ts',
        'src/ui/search-modal-hotkeys.test.ts',
        'src/ui/search-modal-size.test.ts',
        'src/ui/search-modal-tab-dispatch.test.ts',
        'src/ui/title-nav-coverage.test.ts',
    ],
    'cli-ux': [
        'src/app/cli-handlers.test.ts',
        'src/app/confirm-modal.test.ts',
        'src/app/insert-link.test.ts',
        'src/app/layout-ready.test.ts',
        'src/app/open-target.test.ts',
        'src/index/open-recovery.test.ts',
    ],
    'platform': [
        'src/app/plugin-schedulers.test.ts',
        'src/app/task-context.test.ts',
        'src/diagnostics/diagnostic-report.test.ts',
        'src/diagnostics/forensics.test.ts',
        'src/diagnostics/json-text.test.ts',
        'src/diagnostics/logger.test.ts',
        'src/diagnostics/perf-console.test.ts',
        'src/diagnostics/redact.test.ts',
        'src/diagnostics/session-telemetry.test.ts',
        'src/diagnostics/stall-pattern.test.ts',
        'src/embedding/embedder-lifecycle.test.ts',
        'src/embedding/embedder.test.ts',
        'src/embedding/iframe-runner.test.ts',
        'src/embedding/model-registry.test.ts',
        'src/embedding/platform.test.ts',
        'src/index/pacer.test.ts',
        'src/index/startup-drain.test.ts',
        'src/render/recents.test.ts',
        'src/search/pool.test.ts',
        'src/search/prop-normalize.test.ts',
        'src/sidecar/gzip.test.ts',
        'src/test-harness/functional-telemetry/parse-functional-trace.test.ts',
        'src/test-harness/startup-metrics/startup-metrics.test.ts',
        'src/test-harness/startup-response/modal-ready-contract.test.ts',
        'src/test-harness/startup-response/startup-response.test.ts',
        'src/types/settings-migrate.test.ts',
    ],
} as const;

export type CiTestArea = keyof typeof CI_TEST_AREAS;
